# Country.create([{english_name: 'afghanistan', name: 'afganistán', abbreviation: 'af', code: '004'},
# {english_name: 'aland islands', name: 'islas de åland', abbreviation: 'ax', code: '248'},
# {english_name: 'albania', name: 'albania', abbreviation: 'al', code: '008'},
# {english_name: 'algeria', name: 'argelia', abbreviation: 'ag', code: '012'},
# {english_name: 'american samoa', name: 'samoa americana', abbreviation: 'aq', code: '016'},
# {english_name: 'andorra', name: 'andorra', abbreviation: 'an', code: '020'},
# {english_name: 'angola', name: 'angola', abbreviation: 'ao', code: '024'},
# {english_name: 'anguilla', name: 'anguila', abbreviation: 'av', code: '660'},
# {english_name: 'antarctica', name: 'antartica', abbreviation: 'ay', code: '010'},
# {english_name: 'antigua and barbuda', name: 'antigua & barbuda', abbreviation: 'ac', code: '028'},
# {english_name: 'argentina', name: 'argentina', abbreviation: 'ar', code: '032'},
# {english_name: 'armenia', name: 'armenia', abbreviation: 'am', code: '051'},
# {english_name: 'aruba', name: 'aruba', abbreviation: 'aa', code: '533'},
# {english_name: 'australia', name: 'australia', abbreviation: 'as', code: '036'},
# {english_name: 'austria', name: 'austria', abbreviation: 'au', code: '040'},
# {english_name: 'azerbaijan', name: 'azerbaiyán', abbreviation: 'aj', code: '031'},
# {english_name: 'bahamas, the', name: 'las bahamas', abbreviation: 'bf', code: '044'},
# {english_name: 'bahrain', name: 'barein', abbreviation: 'ba', code: '048'},
# {english_name: 'bangladesh', name: 'bangladesh', abbreviation: 'bg', code: '050'},
# {english_name: 'barbados', name: 'barbados', abbreviation: 'bb', code: '052'},
# {english_name: 'belarus', name: 'bielorrusia', abbreviation: 'bo', code: '112'},
# {english_name: 'belgium', name: 'bélgica', abbreviation: 'be', code: '056'},
# {english_name: 'belize', name: 'belice', abbreviation: 'bh', code: '084'},
# {english_name: 'benin', name: 'benin', abbreviation: 'bn', code: '204'},
# {english_name: 'bermuda', name: 'bermuda', abbreviation: 'bd', code: '060'},
# {english_name: 'bhutan', name: 'bután', abbreviation: 'bt', code: '064'},
# {english_name: 'bolivia', name: 'bolivia', abbreviation: 'bl', code: '068'},
# {english_name: 'bosnia and herzegovina', name: 'bosnia y herzegovina', abbreviation: 'bk', code: '070'},
# {english_name: 'botswana', name: 'botsuana', abbreviation: 'bc', code: '072'},
# {english_name: 'bouvet island', name: 'isla bouvet', abbreviation: 'bv', code: '074'},
# {english_name: 'br indian ocean terr', name: 'territorio británico oce. indico', abbreviation: 'io', code: '086'},
# {english_name: 'brazil', name: 'brasil', abbreviation: 'br', code: '076'},
# {english_name: 'british virgin is.', name: 'islas vírgenes', abbreviation: 'vi', code: '092'},
# {english_name: 'brunei', name: 'brunei', abbreviation: 'bx', code: '096'},
# {english_name: 'bulgaria', name: 'bulgaria', abbreviation: 'bu', code: '100'},
# {english_name: 'burkina', name: 'burkina', abbreviation: 'uv', code: '854'},
# {english_name: 'burma', name: 'burma', abbreviation: 'bm', code: '104'},
# {english_name: 'burundi', name: 'burundi', abbreviation: 'by', code: '108'},
# {english_name: 'cambodia', name: 'camboya', abbreviation: 'cb', code: '116'},
# {english_name: 'cameroon', name: 'camerún', abbreviation: 'cm', code: '120'},
# {english_name: 'canada', name: 'canadá', abbreviation: 'ca', code: '124'},
# {english_name: 'cape verde', name: 'cabo verde', abbreviation: 'cv', code: '132'},
# {english_name: 'cayman islands', name: 'islas caimán', abbreviation: 'cj', code: '136'},
# {english_name: 'central african rep.', name: 'república centroafricana', abbreviation: 'ct', code: '140'},
# {english_name: 'chad', name: 'chad', abbreviation: 'cd', code: '148'},
# {english_name: 'chile', name: 'chile', abbreviation: 'ci', code: '152'},
# {english_name: 'china', name: 'china', abbreviation: 'ch', code: '156'},
# {english_name: 'christmas island', name: 'isla de navidad', abbreviation: 'kt', code: '162'},
# {english_name: 'cocos (keeling) islands', name: 'islas cocos', abbreviation: 'ck', code: '166'},
# {english_name: 'colombia', name: 'colombia', abbreviation: 'co', code: '170'},
# {english_name: 'comoros', name: 'comoros', abbreviation: 'cn', code: '174'},
# {english_name: 'congo', name: 'congo', abbreviation: 'cf', code: '178'},
# {english_name: 'congo, democratic republic of the', name: 'república democrática del congo', abbreviation: 'cg', code: '180'},
# {english_name: 'cook islands', name: 'islas cook', abbreviation: 'cw', code: '184'},
# {english_name: 'costa rica', name: 'costa rica', abbreviation: 'cs', code: '188'},
# {english_name: "cote d'ivoire", name: 'costa de marfil', abbreviation: 'iv', code: '384'},
# {english_name: 'croatia', name: 'croacia', abbreviation: 'hr', code: '191'},
# {english_name: 'cuba', name: 'cuba', abbreviation: 'cu', code: '192'},
# {english_name: 'cyprus', name: 'chipre', abbreviation: 'cy', code: '196'},
# {english_name: 'czech republic', name: 'república checa', abbreviation: 'ez', code: '203'},
# {english_name: 'denmark', name: 'dinamarca', abbreviation: 'da', code: '208'},
# {english_name: 'dijibouti', name: 'yibuti', abbreviation: 'dj', code: '262'},
# {english_name: 'dominica', name: 'dominica', abbreviation: 'do', code: '212'},
# {english_name: 'dominican republic', name: 'república dominicana', abbreviation: 'dr', code: '214'},
# {english_name: 'ecuador', name: 'ecuador', abbreviation: 'ec', code: '218'},
# {english_name: 'egypt', name: 'egipto', abbreviation: 'eg', code: '818'},
# {english_name: 'el salvador', name: 'el salvador', abbreviation: 'es', code: '222'},
# {english_name: 'equatorial guinea', name: 'guinea ecuatorial', abbreviation: 'ek', code: '226'},
# {english_name: 'eritrea', name: 'eritrea', abbreviation: 'er', code: '232'},
# {english_name: 'estonia', name: 'estonia', abbreviation: 'en', code: '233'},
# {english_name: 'ethiopia', name: 'etiopía', abbreviation: 'et', code: '231'},
# {english_name: 'falkland (is malvinas)', name: 'islas malvinas', abbreviation: 'fk', code: '238'},
# {english_name: 'faroe islands', name: 'islas faroe', abbreviation: 'fo', code: '234'},
# {english_name: 'fed states micronesia', name: 'estados federados de micronesia', abbreviation: 'fm', code: '583'},
# {english_name: 'fiji', name: 'fiji', abbreviation: 'fj', code: '242'},
# {english_name: 'finland', name: 'finlandia', abbreviation: 'fi', code: '246'},
# {english_name: 'fr so & antarctic lnds', name: 'tierras australes y antárticas francesas', abbreviation: 'fs', code: '260'},
# {english_name: 'france', name: 'francia', abbreviation: 'fr', code: '250'},
# {english_name: 'french guiana', name: 'guyana francesa', abbreviation: 'fg', code: '254'},
# {english_name: 'french polynesia', name: 'polinesia francesa', abbreviation: 'fp', code: '258'},
# {english_name: 'gabon', name: 'gabón', abbreviation: 'gb', code: '266'},
# {english_name: 'gambia, the', name: 'gambia', abbreviation: 'ga', code: '270'},
# {english_name: 'georgia', name: 'georgia', abbreviation: 'gg', code: '268'},
# {english_name: 'germany', name: 'alemania', abbreviation: 'gm', code: '276'},
# {english_name: 'ghana', name: 'ghana', abbreviation: 'gh', code: '288'},
# {english_name: 'gibraltar', name: 'gibraltar', abbreviation: 'gi', code: '292'},
# {english_name: 'greece', name: 'grecia', abbreviation: 'gr', code: '300'},
# {english_name: 'greenland', name: 'groenlandia', abbreviation: 'gl', code: '304'},
# {english_name: 'grenada', name: 'granada', abbreviation: 'gj', code: '308'},
# {english_name: 'guadeloupe', name: 'guadalupe', abbreviation: 'gp', code: '312'},
# {english_name: 'guam', name: 'guam', abbreviation: 'gq', code: '316'},
# {english_name: 'guatemala', name: 'guatemala', abbreviation: 'gt', code: '320'},
# {english_name: 'guernsey', name: 'guernsey', abbreviation: 'gk', code: '831'},
# {english_name: 'guinea', name: 'guinea', abbreviation: 'gv', code: '324'},
# {english_name: 'guinea-bissau', name: 'guinea-bissau', abbreviation: 'pu', code: '624'},
# {english_name: 'guyana', name: 'guyana', abbreviation: 'gy', code: '328'},
# {english_name: 'haiti', name: 'haití', abbreviation: 'ha', code: '332'},
# {english_name: 'heard is&mcdonald isls', name: 'islas heard y mcdonald', abbreviation: 'hm', code: '334'},
# {english_name: 'honduras', name: 'honduras', abbreviation: 'ho', code: '340'},
# {english_name: 'hong kong', name: 'hong kong', abbreviation: 'hk', code: '344'},
# {english_name: 'hungary', name: 'hungría', abbreviation: 'hu', code: '348'},
# {english_name: 'iceland', name: 'islandia', abbreviation: 'ic', code: '352'},
# {english_name: 'india', name: 'india', abbreviation: 'in', code: '356'},
# {english_name: 'indonesia', name: 'indonesia', abbreviation: 'id', code: '360'},
# {english_name: 'iran', name: 'irán', abbreviation: 'ir', code: '364'},
# {english_name: 'iraq', name: 'irak', abbreviation: 'iz', code: '368'},
# {english_name: 'ireland', name: 'irlanda', abbreviation: 'ei', code: '372'},
# {english_name: 'israel', name: 'israel', abbreviation: 'is', code: '376'},
# {english_name: 'italy', name: 'italia', abbreviation: 'it', code: '380'},
# {english_name: 'jamaica', name: 'jamaica', abbreviation: 'jm', code: '388'},
# {english_name: 'japan', name: 'japón', abbreviation: 'ja', code: '392'},
# {english_name: 'jersey', name: 'jersey', abbreviation: 'je', code: '832'},
# {english_name: 'jordan', name: 'jordania', abbreviation: 'jo', code: '400'},
# {english_name: 'kazakhstan', name: 'kazajistán', abbreviation: 'kz', code: '398'},
# {english_name: 'kenya', name: 'kenia', abbreviation: 'ke', code: '404'},
# {english_name: 'kiribati', name: 'kiribati', abbreviation: 'kr', code: '296'},
# {english_name: 'korea, republic of', name: 'corea del sur', abbreviation: 'ks', code: '410'},
# {english_name: 'korea,dem peoples rep', name: 'corea del norte', abbreviation: 'kn', code: '408'},
# {english_name: 'kuwait', name: 'kuwait', abbreviation: 'ku', code: '414'},
# {english_name: 'kyrgyzstan', name: 'kirguistán', abbreviation: 'kg', code: '417'},
# {english_name: 'laos', name: 'laos', abbreviation: 'la', code: '418'},
# {english_name: 'latvia', name: 'letonia', abbreviation: 'lg', code: '428'},
# {english_name: 'lebanon', name: 'líbano', abbreviation: 'le', code: '422'},
# {english_name: 'lesotho', name: 'lesoto', abbreviation: 'lt', code: '426'},
# {english_name: 'liberia', name: 'liberia', abbreviation: 'li', code: '430'},
# {english_name: 'libya', name: 'libia', abbreviation: 'ly', code: '434'},
# {english_name: 'liechtenstein', name: 'liechtenstein', abbreviation: 'ls', code: '438'},
# {english_name: 'lithuania', name: 'lituania', abbreviation: 'lh', code: '440'},
# {english_name: 'luxembourg', name: 'luxemburgo', abbreviation: 'lu', code: '442'},
# {english_name: 'macau', name: 'macao', abbreviation: 'mc', code: '446'},
# {english_name: 'macedonia', name: 'macedonia', abbreviation: 'mk', code: '807'},
# {english_name: 'madagascar', name: 'madagascar', abbreviation: 'ma', code: '450'},
# {english_name: 'malawi', name: 'malawi', abbreviation: 'mi', code: '454'},
# {english_name: 'malaysia', name: 'malasia', abbreviation: 'my', code: '458'},
# {english_name: 'maldives', name: 'maldivas', abbreviation: 'mv', code: '462'},
# {english_name: 'mali', name: 'mali', abbreviation: 'ml', code: '466'},
# {english_name: 'malta', name: 'malta', abbreviation: 'mt', code: '470'},
# {english_name: 'man, isle of', name: 'isla de man', abbreviation: 'im', code: '833'},
# {english_name: 'marshall islands', name: 'islas marshall', abbreviation: 'rm', code: '584'},
# {english_name: 'martinique', name: 'martinica', abbreviation: 'mb', code: '474'},
# {english_name: 'mauritania', name: 'mauritania', abbreviation: 'mr', code: '478'},
# {english_name: 'mauritius', name: 'mauricio', abbreviation: 'mp', code: '480'},
# {english_name: 'mayotte', name: 'mayotte', abbreviation: 'mf', code: '175'},
# {english_name: 'mexico', name: 'méxico', abbreviation: 'mx', code: '484'},
# {english_name: 'moldova', name: 'moldavia', abbreviation: 'md', code: '498'},
# {english_name: 'monaco', name: 'mónaco', abbreviation: 'mn', code: '492'},
# {english_name: 'mongolia', name: 'mongolia', abbreviation: 'mg', code: '496'},
# {english_name: 'montenegro', name: 'montenegro', abbreviation: 'mj', code: '499'},
# {english_name: 'montserrat', name: 'montserrat', abbreviation: 'ms', code: '500'},
# {english_name: 'morocco', name: 'marruecos', abbreviation: 'mo', code: '504'},
# {english_name: 'mozambique', name: 'mozambique', abbreviation: 'mz', code: '508'},
# {english_name: 'namibia', name: 'namibia', abbreviation: 'wa', code: '516'},
# {english_name: 'nauru', name: 'nauru', abbreviation: 'nr', code: '520'},
# {english_name: 'nepal', name: 'nepal', abbreviation: 'np', code: '524'},
# {english_name: 'netherlands', name: 'holanda', abbreviation: 'nl', code: '528'},
# {english_name: 'netherlands antilles', name: 'antillas holandesas', abbreviation: 'nt', code: '530'},
# {english_name: 'new caledonia', name: 'nueva caledonia', abbreviation: 'nc', code: '540'},
# {english_name: 'new zealand', name: 'nueva zelandia', abbreviation: 'nz', code: '554'},
# {english_name: 'nicaragua', name: 'nicaragua', abbreviation: 'nu', code: '558'},
# {english_name: 'niger', name: 'níger', abbreviation: 'ng', code: '562'},
# {english_name: 'nigeria', name: 'nigeria', abbreviation: 'ni', code: '566'},
# {english_name: 'niue', name: 'niue', abbreviation: 'ne', code: '570'},
# {english_name: 'norfolk island', name: 'isla norfolk', abbreviation: 'nf', code: '574'},
# {english_name: 'northern mariana is', name: 'islas marianas del norte', abbreviation: 'cq', code: '580'},
# {english_name: 'norway', name: 'noruega', abbreviation: 'no', code: '578'},
# {english_name: 'oman', name: 'omán', abbreviation: 'mu', code: '512'},
# {english_name: 'pakistan', name: 'pakistán', abbreviation: 'pk', code: '586'},
# {english_name: 'palestinian territory, occupied', name: 'territorio palestino ocupado', abbreviation: 'ps', code: '275'},
# {english_name: 'panama', name: 'panamá', abbreviation: 'pa', code: '591'},
# {english_name: 'papua new guinea', name: 'papua nueva guinea', abbreviation: 'pp', code: '598'},
# {english_name: 'paraguay', name: 'paraguay', abbreviation: 'py', code: '600'},
# {english_name: 'palau republic of', name: 'palaos', abbreviation: 'ps', code: '275'},
# {english_name: 'peru', name: 'perú', abbreviation: 'pe', code: '604'},
# {english_name: 'philippines', name: 'filipinas', abbreviation: 'rp', code: '608'},
# {english_name: 'pitcairn islands', name: 'islas pitcáirn', abbreviation: 'pc', code: '612'},
# {english_name: 'poland', name: 'polonia', abbreviation: 'pl', code: '616'},
# {english_name: 'portugal', name: 'portugal', abbreviation: 'po', code: '620'},
# {english_name: 'puerto rico', name: 'puerto rico', abbreviation: 'rq', code: '630'},
# {english_name: 'qatar', name: 'catar', abbreviation: 'qa', code: '634'},
# {english_name: 'reunion', name: 'reunión', abbreviation: 're', code: '638'},
# {english_name: 'romania', name: 'rumania', abbreviation: 'ro', code: '642'},
# {english_name: 'russia', name: 'rusia', abbreviation: 'rs', code: '643'},
# {english_name: 'rwanda', name: 'ruanda', abbreviation: 'rw', code: '646'},
# {english_name: 's.georgia/s.sandwic is', name: 'islas georgia del sur y sandwich del sur', abbreviation: 'sx', code: '239'},
# {english_name: 'san marino', name: 'san marino', abbreviation: 'sm', code: '674'},
# {english_name: 'sao tome and principe', name: 'santo tomé y principe', abbreviation: 'tp', code: '678'},
# {english_name: 'saudi arabia', name: 'arabia saudita', abbreviation: 'sa', code: '682'},
# {english_name: 'senegal', name: 'senegal', abbreviation: 'sg', code: '686'},
# {english_name: 'serbia', name: 'serbia', abbreviation: 'ri', code: '688'},
# {english_name: 'seychelles', name: 'seychelles', abbreviation: 'se', code: '690'},
# {english_name: 'sierra leone', name: 'sierra leona', abbreviation: 'sl', code: '694'},
# {english_name: 'singapore', name: 'singapur', abbreviation: 'sn', code: '702'},
# {english_name: 'slovakia', name: 'eslovaquia', abbreviation: 'lo', code: '703'},
# {english_name: 'slovenia', name: 'eslovenia', abbreviation: 'si', code: '705'},
# {english_name: 'solomon islands', name: 'islas salomón', abbreviation: 'bp', code: '090'},
# {english_name: 'somalia', name: 'somalia', abbreviation: 'so', code: '706'},
# {english_name: 'south africa', name: 'sudáfica', abbreviation: 'sf', code: '710'},
# {english_name: 'south sudan', name: 'sudán de sur', abbreviation: 'od', code: '728'},
# {english_name: 'spain', name: 'españa', abbreviation: 'sp', code: '724'},
# {english_name: 'sri lanka', name: 'sri lanka', abbreviation: 'ce', code: '144'},
# {english_name: 'st lucia', name: 'santa lucía', abbreviation: 'st', code: '662'},
# {english_name: 'st. helena', name: 'isla santa elena', abbreviation: 'sh', code: '654'},
# {english_name: 'st. kitts and nevis', name: 'san crisóbal y nieves', abbreviation: 'sc', code: '659'},
# {english_name: 'st. pierre and miquelon', name: 'san pedro y miguelón', abbreviation: 'sb', code: '666'},
# {english_name: 'st. vincent/grenadines', name: 'san vicente y las granadinas', abbreviation: 'vc', code: '670'},
# {english_name: 'st.barthelemy', name: 'san bartolomé', abbreviation: 'bl', code: '652'},
# {english_name: 'st.martin', name: 'isla de san martín', abbreviation: 'mf', code: '663'},
# {english_name: 'sudan', name: 'sudán', abbreviation: 'su', code: '736'},
# {english_name: 'suriname', name: 'surinam', abbreviation: 'ns', code: '740'},
# {english_name: 'swaziland', name: 'suazilandia', abbreviation: 'wz', code: '748'},
# {english_name: 'sweden', name: 'suecia', abbreviation: 'sw', code: '752'},
# {english_name: 'switzerland', name: 'suiza', abbreviation: 'sz', code: '756'},
# {english_name: 'syria', name: 'siria', abbreviation: 'sy', code: '760'},
# {english_name: 'taiwan', name: 'taiwán', abbreviation: 'tw', code: '158'},
# {english_name: 'tajikistan', name: 'tajikistán', abbreviation: 'ti', code: '762'},
# {english_name: 'tanzania, united rep of', name: 'tanzania', abbreviation: 'tz', code: '834'},
# {english_name: 'thailand', name: 'tailandia', abbreviation: 'th', code: '764'},
# {english_name: 'timor-leste', name: 'timor oriental', abbreviation: 'tt', code: '626'},
# {english_name: 'togo', name: 'togo', abbreviation: 'to', code: '768'},
# {english_name: 'tokelau', name: 'tokelau', abbreviation: 'tl', code: '772'},
# {english_name: 'tonga', name: 'tonga', abbreviation: 'tn', code: '776'},
# {english_name: 'trinidad and tobago', name: 'trinidad y tobago', abbreviation: 'td', code: '780'},
# {english_name: 'tunisia', name: 'túnez', abbreviation: 'ts', code: '788'},
# {english_name: 'turkey', name: 'turquía', abbreviation: 'tu', code: '792'},
# {english_name: 'turkmenistan', name: 'turkmenistán', abbreviation: 'tx', code: '795'},
# {english_name: 'turks and caicos isl', name: 'islas turcas y caicos', abbreviation: 'tk', code: '796'},
# {english_name: 'tuvalu', name: 'tuvalu', abbreviation: 'tv', code: '798'},
# {english_name: 'u.s. minor outlying isl', name: 'islas ultramarinas e.e.u.u', abbreviation: 'um', code: '581'},
# {english_name: 'uganda', name: 'uganda', abbreviation: 'ug', code: '800'},
# {english_name: 'ukraine', name: 'ucraina', abbreviation: 'up', code: '804'},
# {english_name: 'united arab emirates', name: 'emirato árabes unidos', abbreviation: 'ae', code: '784'},
# {english_name: 'united kingdom', name: 'reino unido', abbreviation: 'uk', code: '826'},
# {english_name: 'united states', name: 'estados unidos', abbreviation: 'us', code: '840'},
# {english_name: 'uruguay', name: 'uruguay', abbreviation: 'uy', code: '858'},
# {english_name: 'uzbekistan', name: 'uzbekistán', abbreviation: 'uz', code: '860'},
# {english_name: 'vanuatu', name: 'vanuatu', abbreviation: 'nh', code: '548'},
# {english_name: 'vatican city', name: 'ciudad del vaticano', abbreviation: 'vt', code: '336'},
# {english_name: 'venezuela', name: 'venezuela', abbreviation: 've', code: '862'},
# {english_name: 'vietnam', name: 'vietnam', abbreviation: 'vm', code: '704'},
# {english_name: 'virgin islands', name: 'islas vírgenes', abbreviation: 'vq', code: '850'},
# {english_name: 'wallis and futuna', name: 'wallis y futuna', abbreviation: 'wf', code: '876'},
# {english_name: 'western sahara', name: 'sahara occidental', abbreviation: 'wi', code: '732'},
# {english_name: 'western samoa', name: 'samoa occidental', abbreviation: 'ws', code: '882'},
# {english_name: 'yemen', name: 'yemén', abbreviation: 'ym', code: '887'},
# {english_name: 'zambia', name: 'zambia', abbreviation: 'za', code: '894'},
# {english_name: 'zimbabwe', name: 'zimbabue', abbreviation: 'zi', code: '716'}])